# Create TradetoGDP.csv
- need gdp.csv

In [1]:
import os
print(os.getcwd())

C:\Users\dimpa\DataSciCertWorkSpace\Group project\Code

In [2]:

import pandas as pd
gdp = pd.read_csv("../RawData/gdp.csv")

In [3]:
gdp["Geography"] = gdp["Geography"].fillna(method="ffill")
gdp["North American Industry Classification System (NAICS)"] = gdp["North American Industry Classification System (NAICS)"].fillna(method="ffill")

gdp.head(30)

,Geography,North American Industry Classification System (NAICS),REF-Date,GDP
0,Newfoundland and Labrador,All industries [T001] 5,2013,"30,873.00"
1,Newfoundland and Labrador,All industries [T001] 5,2014,"30,563.20"
2,Newfoundland and Labrador,All industries [T001] 5,2015,"30,194.20"
3,Newfoundland and Labrador,All industries [T001] 5,2016,"30,602.90"
4,Newfoundland and Labrador,All industries [T001] 5,2017,"31,002.70"
5,Newfoundland and Labrador,All industries [T001] 5,2018,"30,178.90"
6,Newfoundland and Labrador,All industries [T001] 5,2019,"31,359.10"
7,Newfoundland and Labrador,All industries [T001] 5,2020,"29,914.20"
8,Newfoundland and Labrador,All industries [T001] 5,2021,"30,230.70"
9,Newfoundland and Labrador,All industries [T001] 5,2022,"29,902.10"
10,Newfoundland and Labrador,All industries [T001] 5,2023,"28,949.30"
11,Newfoundland and Labrador,"Agriculture, forestry, fishing and hunting [11]",2013,902.3
12,Newfoundland and Labrador,"Agriculture, forestry, fishing and hunting [11]",2014,765.6
13,Newfoundland and Labrador,"Agriculture, forestry, fishing and hunting [11]",2015,783.6
14,Newfoundland and Labrador,"Agriculture, forestry, fishing and hunting [11]",2016,683.5
15,Newfoundland and Labrador,"Agriculture, forestry, fishing and hunting [11]",2017,596.9
16,Newfoundland and Labrador,"Agriculture, forestry, fishing and hunting [11]",2018,556.4
17,Newfoundland and Labrador,"Agriculture, forestry, fishing and hunting [11]",2019,508.1
18,Newfoundland and Labrador,"Agriculture, forestry, fishing and hunting [11]",2020,460.4
19,Newfoundland and Labrador,"Agriculture, forestry, fishing and hunting [11]",2021,550.2
20,Newfoundland and Labrador,"Agriculture, forestry, fishing and hunting [11]",2022,619.8
21,Newfoundland and Labrador,"Agriculture, forestry, fishing and hunting [11]",2023,605.6
22,Newfoundland and Labrador,"Mining, quarrying, and oil and gas extraction ...",2013,"6,777.80"
23,Newfoundland and Labrador,"Mining, quarrying, and oil and gas extraction ...",2014,"6,385.30"
24,Newfoundland and Labrador,"Mining, quarrying, and oil and gas extraction ...",2015,"5,827.70"
25,Newfoundland and Labrador,"Mining, quarrying, and oil and gas extraction ...",2016,"6,658.00"
26,Newfoundland and Labrador,"Mining, quarrying, and oil and gas extraction ...",2017,"7,311.50"
27,Newfoundland and Labrador,"Mining, quarrying, and oil and gas extraction ...",2018,"7,147.40"
28,Newfoundland and Labrador,"Mining, quarrying, and oil and gas extraction ...",2019,"8,162.20"
29,Newfoundland and Labrador,"Mining, quarrying, and oil and gas extraction ...",2020,"8,473.60"

In [4]:
gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3003 entries, 0 to 3002
Data columns (total 4 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   Geography                                              3003 non-null   object
 1   North American Industry Classification System (NAICS)  3003 non-null   object
 2   REF-Date                                               3003 non-null   int64
 3   GDP                                                    3003 non-null   object
dtypes: int64(1), object(3)
memory usage: 94.0+ KB

In [5]:
gdp["industry"] = gdp["North American Industry Classification System (NAICS)"].str.extract("(\d+)")
gdp["industry"] = gdp["industry"].fillna(0).astype(int)
gdp["industry"] = gdp["industry"].astype(int)
gdp.head()

,Geography,North American Industry Classification System (NAICS),REF-Date,GDP,industry
0,Newfoundland and Labrador,All industries [T001] 5,2013,"30,873.00",1
1,Newfoundland and Labrador,All industries [T001] 5,2014,"30,563.20",1
2,Newfoundland and Labrador,All industries [T001] 5,2015,"30,194.20",1
3,Newfoundland and Labrador,All industries [T001] 5,2016,"30,602.90",1
4,Newfoundland and Labrador,All industries [T001] 5,2017,"31,002.70",1

In [6]:
gdp = gdp.drop(columns=["North American Industry Classification System (NAICS)"])
gdp["GDP"] = gdp["GDP"].str.replace(",", "").astype(float).astype(int)
gdp.head()

                   Geography  REF-Date    GDP  industry
0  Newfoundland and Labrador      2013  30873         1
1  Newfoundland and Labrador      2014  30563         1
2  Newfoundland and Labrador      2015  30194         1
3  Newfoundland and Labrador      2016  30602         1
4  Newfoundland and Labrador      2017  31002         1

In [7]:
gdp = gdp.rename(columns={"REF-Date": "REF_DATE"})
gdp = gdp.rename(columns={"Geography": "Province"})
gdp.head()

                    Province  REF_DATE    GDP  industry
0  Newfoundland and Labrador      2013  30873         1
1  Newfoundland and Labrador      2014  30563         1
2  Newfoundland and Labrador      2015  30194         1
3  Newfoundland and Labrador      2016  30602         1
4  Newfoundland and Labrador      2017  31002         1

In [8]:
gdp["industry"] = gdp["industry"].replace(1, 0)
gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3003 entries, 0 to 3002
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Province  3003 non-null   object
 1   REF_DATE  3003 non-null   int64
 2   GDP       3003 non-null   int32
 3   industry  3003 non-null   int32
dtypes: int32(2), int64(1), object(1)
memory usage: 70.5+ KB

In [9]:
# gdp = gdp.drop(columns=["North American Industry Classification System (NAICS)"])

print(gdp["industry"].unique())
print(gdp["Province"].unique())

# gdp.head(250)
gdp.count()
# merge key gdp and export inport csv
# trade = pd.merge(merged, df3, on=["Province", "REF_DATE", "industry"], how="left")

[ 0 11 21 22 23 31 41 44 48 51 52 53 54 55 56 61 62 71 72 81 91]
['Newfoundland and Labrador' 'Prince Edward Island' 'Nova Scotia'
 'New Brunswick' 'Quebec' 'Ontario' 'Manitoba' 'Saskatchewan' 'Alberta'
 'British Columbia' 'Yukon' 'Northwest Territories' 'Nunavut']

Province    3003
REF_DATE    3003
GDP         3003
industry    3003
dtype: int64

In [10]:
gdp.to_csv("../Src/TradetoGDP.csv", index=False)
print("Trade csv created in folder ../Src/TradetoGDP.csv")

Trade csv created in folder ../Src/TradetoGDP.csv

In [ ]:
# merged.to_csv("../Src/TradeExposurebyIndustry.csv", index=False)
# print(merged)